### ISSUE TITLE
bug when i remove an endpoint

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/automatic-monitoring-dashboard#28]
it seems that if i remove an endopint, (e.g. the commented out here: https://github.com/mircealungu/Zeeguu-API/blob/master/zeeguu_api/api/feeds.py#L300) the dashboard crashes on startup. can you have a look at this? 

```
[Sat Jun 24 08:48:15.975501 2017] [wsgi:error] [pid 25280:tid 139895168640768] [remote 130.92.64.84:36387] KeyError: 'api.get_feed_items_for'
[Sat Jun 24 08:48:16.020493 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388] mod_wsgi (pid=25280): Exception occurred processing WSGI script '/home/mircea/zee/http/api/zeeguu_api.wsgi'.
[Sat Jun 24 08:48:16.020730 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388] Traceback (most recent call last):
[Sat Jun 24 08:48:16.020813 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1997, in __call__
[Sat Jun 24 08:48:16.020822 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     return self.wsgi_app(environ, start_response)
[Sat Jun 24 08:48:16.020836 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1985, in wsgi_app
[Sat Jun 24 08:48:16.020843 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     response = self.handle_exception(e)
[Sat Jun 24 08:48:16.020875 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask_Cors-3.0.2-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
[Sat Jun 24 08:48:16.020883 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Sat Jun 24 08:48:16.020896 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1540, in handle_exception
[Sat Jun 24 08:48:16.020903 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     reraise(exc_type, exc_value, tb)
[Sat Jun 24 08:48:16.020916 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
[Sat Jun 24 08:48:16.020923 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     raise value
[Sat Jun 24 08:48:16.020935 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1982, in wsgi_app
[Sat Jun 24 08:48:16.020942 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     response = self.full_dispatch_request()
[Sat Jun 24 08:48:16.020955 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1607, in full_dispatch_request
[Sat Jun 24 08:48:16.020963 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     self.try_trigger_before_first_request_functions()
[Sat Jun 24 08:48:16.020976 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1654, in try_trigger_before_first_request_functions
[Sat Jun 24 08:48:16.020983 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     func()
[Sat Jun 24 08:48:16.020996 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]   File "/usr/local/lib/python3.6/site-packages/dashboard-1.5-py3.6.egg/dashboard/measurement.py", line 31, in init_measurement
[Sat Jun 24 08:48:16.021003 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388]     user_app.view_functions[rule.endpoint] = track_performance(user_app.view_functions[rule.endpoint],
[Sat Jun 24 08:48:16.021029 2017] [wsgi:error] [pid 25280:tid 139895051142912] [remote 130.92.64.84:36388] KeyError: 'api.get_feed_items_for'

```

**Comment by FlyingBird95** [comment]
This should be fixed in the latest version (in development) of the dashboard
