### ISSUE TITLE
exception in the deployed version

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/automatic-monitoring-dashboard#37]
looks like this:

```
[Fri Aug 11 13:12:05.653499 2017] [wsgi:error] [pid 31972:tid 140340353804032] Traceback (most recent call last):
[Fri Aug 11 13:12:05.653550 2017] [wsgi:error] [pid 31972:tid 140340353804032]   File "/usr/local/lib/python3.6/site-packages/flask_monitoring_dashboard-1.8-py3.6.egg/dashboard/outlier.py", line 42, in log_stack_trace
[Fri Aug 11 13:12:05.653558 2017] [wsgi:error] [pid 31972:tid 140340353804032]     stack_list.extend(['', str(th)])
[Fri Aug 11 13:12:05.653573 2017] [wsgi:error] [pid 31972:tid 140340353804032]   File "/usr/local/lib/python3.6/threading.py", line 819, in __repr__
[Fri Aug 11 13:12:05.653579 2017] [wsgi:error] [pid 31972:tid 140340353804032]     self.is_alive() # easy way to get ._is_stopped set when appropriate
[Fri Aug 11 13:12:05.653592 2017] [wsgi:error] [pid 31972:tid 140340353804032]   File "/usr/local/lib/python3.6/threading.py", line 1115, in is_alive
[Fri Aug 11 13:12:05.653599 2017] [wsgi:error] [pid 31972:tid 140340353804032]     self._wait_for_tstate_lock(False)
[Fri Aug 11 13:12:05.653612 2017] [wsgi:error] [pid 31972:tid 140340353804032]   File "/usr/local/lib/python3.6/threading.py", line 1071, in _wait_for_tstate_lock
[Fri Aug 11 13:12:05.653619 2017] [wsgi:error] [pid 31972:tid 140340353804032]     assert self._is_stopped
```

do you have any idea why?

**Comment by mircealungu** [comment]
Guys, did you have the chance to look into this?

**Comment by mircealungu** [comment]
I still have a lot of exceptions polluting the log files.
